# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanMVVM
  pod 'RxSwift', '5.1.0'
  pod 'RxCocoa', '5.1.0'
  pod 'RxDataSources', '4.0.1'
  pod 'RxOptional', '4.1.0'

  target 'CleanMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanMVVMUITests' do
    # Pods for testing
  end

end
